on:
  pull_request:
    types: [opened, synchronize]
jobs:
  secrets:
    name: Create env file with gh secrets
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          check-latest: true
      - run: yarn install
      - run: |
          touch .env
          echo SEED_LAW_COOK=${{ secrets.SEED_LAW_COOK }} >> .env
          echo SEED_PEACE_GLOBE=${{ secrets.SEED_PEACE_GLOBE }} >> .env
          echo SEED_SWALLOW_HEALTH=${{ secrets.SEED_SWALLOW_HEALTH }} >> .env
